services:

  api-gateway:
    container_name: api-gateway
    restart: unless-stopped
    build:
      context: ./server/ApiGateway
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./server/ApiGateway/nginx.conf:/etc/nginx/nginx.conf
      - ./server/ApiGateway/certificates/localhost.key:/etc/nginx/certificates/localhost.key
      - ./server/ApiGateway/certificates/localhost.crt:/etc/nginx/certificates/localhost.crt
    extra_hosts:
      - "host.docker.internal:host-gateway"

  user-service:
    container_name: user-service
    restart: unless-stopped
    build:
      context: .
      dockerfile: server/UsersDockerfile
    ports:
      - "7001:7001"
    environment:
      - APP_PORT=7001
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTION_STRING=Host=user-postgres;Port=5432;Database=cinema_users;Username=postgres;Password=1;Timezone=Europe/Minsk;
    volumes:
      - ./server/ApiGateway/certificates/localhost.pfx:/app/localhost.pfx  


  movie-service:
    container_name: movie-service
    restart: unless-stopped
    build:
      context: .
      dockerfile: server/MoviesDockerfile
    ports:
      - "7002:7002"
    environment:
      - APP_PORT=7002
      - USERS_APP_PORT=7001
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTION_STRING=Host=movie-postgres;Port=5432;Database=cinema_movies;Username=postgres;Password=1;Timezone=Europe/Minsk;
      - REDIS_CONFIGURATION=redis:6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=15672
    volumes:
      - ./server/ApiGateway/certificates/localhost.pfx:/app/localhost.pfx  


  booking-service:
    container_name: booking-service
    restart: unless-stopped
    build:
      context: .
      dockerfile: server/BookingsDockerfile
    ports:
      - "7003:7003"
    environment:
      - APP_PORT=7003
      - USERS_APP_PORT=7001
      - MOVIES_APP_PORT=7002
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTION_STRING=mongodb://root:password@mongodb:27017/CinemaBookings/?authSource=admin&authMechanism=SCRAM-SHA-1
      - DATABASE_NAME=CinemaBookings
      - REDIS_CONFIGURATION=redis:6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=15672
    volumes:
      - ./server/ApiGateway/certificates/localhost.pfx:/app/localhost.pfx


  user-postgres:
    container_name: user-postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: cinema_users
    ports:
      - "5433:5432"
    volumes:
      - user-postgres-data:/var/lib/postgresql/data


  movie-postgres:
    container_name: movie-postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: cinema_movies
    ports:
      - "5434:5432"
    volumes:
      - movie-postgres-data:/var/lib/postgresql/data


  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=password
    - MONGO_INITDB_DATABASE=admin
    command: ["mongod", "--auth"]
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db


  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: 1
    ports:
      - 6379:6379


  rabbitmq:
    container_name: rabbit-mq
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    

volumes:
  user-postgres-data:
  movie-postgres-data:
  mongo-data: