services:

  api-gateway:
    container_name: api-gateway
    build:
      context: ./server/ApiGateway
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./server/ApiGateway/nginx.conf:/etc/nginx/nginx.conf
      - ./server/ApiGateway/certificates/localhost.key:/etc/nginx/certificates/localhost.key
      - ./server/ApiGateway/certificates/localhost.crt:/etc/nginx/certificates/localhost.crt
    extra_hosts:
      - "host.docker.internal:host-gateway"

  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: server/UsersDockerfile
    ports:
      - "7001:7001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTION_STRING=Host=postgres;Port=5432;Database=cinema_users;Username=postgres;Password=1;Timezone=Europe/Minsk;
    volumes:
      - ./server/ApiGateway/certificates/localhost.pfx:/app/localhost.pfx  


  movie-service:
    container_name: movie-service
    build:
      context: .
      dockerfile: server/MoviesDockerfile
    ports:
      - "7002:7002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTION_STRING=Host=postgres;Port=5432;Database=cinema_movies;Username=postgres;Password=1;Timezone=Europe/Minsk;
      - REDIS_CONFIGURATION=redis:6379
    volumes:
      - ./server/ApiGateway/certificates/localhost.pfx:/app/localhost.pfx  


#   booking-service:
#     build:
#       context: ./server
#       dockerfile: Microservices/BookingService/BookingService.API/Dockerfile
#     ports:
#       - "5003:5000"
#     depends_on:
#       - postgres
#       - redis
#       - rabbitmq


  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
        # - ./init-scripts:/docker-entrypoint-initdb.d

  # rabbitmq:
  #   container_name: rabbit-mq
  #   image: rabbitmq:3-management-alpine
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   restart: unless-stopped

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    environment:
      REDIS_PASSWORD: 1
    ports:
      - 6379:6379

volumes:
  postgres-data: